# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DMD Electrical
email: david@dmdelectrical.co.za
description: > # this means to ignore newlines until "baseurl:"
  DMD Electrical is a family owned and operated business with over 10 years of industrial and commercial expertise. We service areas in and around Gauteng and its neighbouring provinces. As an owned business we value the importance of our reputation and trust with our customers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmdelectrical.co.za" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dmdelectrical
github_username:  dmdelectrical

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
